environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: PowerShellCore
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: WindowsPowerShell
  snowflake:
    secure: hwdG7JCG0zY1bZ2wfCFoNBdXsWKBEfT+DDnTMi5IzKxDp/6uj1taMBEkynRlCzX0

clone_folder: c:\projects\PSFolderSize

version: 0.1.0.{build}
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
test_script: 
  - ps:   if ($env:PowerShellEdition -eq 'WindowsPowerShell') { . .\build.ps1 -Task Test } 
  - pwsh: if ($env:PowerShellEdition -eq 'PowerShellCore')    { . .\build.ps1 -Task Publish }